version: 1.0.{build}
image: Visual Studio 2015

configuration:
- Debug
- Release

platform:
- Win32

build:
  verbosity: normal
  project: DualServer.sln

after_build:
- cmd: FOR /F %%A IN (BuildTmp\DualServer\%PLATFORM%\%CONFIGURATION%\GIT-VS-VERSION-FILE) DO SET PRODUCT_VERSION=%%A

artifacts:
- path: Build\DualServer\$(platform)\$(configuration)
  name: DualServer_$(PRODUCT_VERSION)-$(platform)-$(configuration)
